---
# .github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false
contact_links:
  - name: GitHub Scripts Community Support
    url: https://github.com/JuanVilla424/scripts/discussions
    about: Please ask and answer questions here.
  - name: GitHub Scripts Security Reports
    url: https://juanvilla424.github.io/scripts/SECURITY
    about: Please report security vulnerabilities here.
